name: Master Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: python-lint
        uses: CyberZHG/github-action-python-lint@0.0.2
        with:
          args: --ignore=E501,E722 src
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: albertowar/locust-newrelic-sidecar
          push: false
